version: "3.8"

services:
  # Nodejs
  result:
    build: ./result
    command: node server.js
    volumes:
      - ./result:/app/result
    container_name: "nodejs"
    ports:
      - "8080"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.1
    networks:
      - devops-network
  # Python
  vote:
    build: ./vote
    command: python app.py
    volumes:
      - ./vote:/app/vote
    container_name: "python"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.1
    networks:
      - devops-network
  # Dotnet
  worker:
    build: ./worker
    container_name: "dotnet"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.1
    networks:
      - devops-network
  # Postgres DB
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.1
    networks:
      - devops-network
    restart: unless-stopped
  # Redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.1
    networks:
      - devops-network
networks:
  devops-network:
